config/routes.rb
Rails.application.routes.draw do
  scope path_names: { new: "novo", edit: "editar" } do
    resources :project_tags, path: "projeto_tags"
    resources :task_cells, path: "tarefas_celulas"
    resources :task_boards, path: "tarefas_diretorias"
    resources :goal_cells, path: "meta_celulas"
    resources :goal_boards, path: "meta_diretorias"
    get "/users/new", to: "users#new"
    post "/users", to: "users#create"
    devise_for :users
    root to:  "static_pages#home"
    
    get "/artigos", to: "posts#articles", as: "articles"
    get "/artigos/novo", to: "posts#new_article", as: "new_article"
    get "/forum", to: "posts#forum"
    get "/tópico/novo", to: "posts#new_question", as: "new_question"
    
    resources :posts, path: "publicações" do
      resources :dislikes, path: "dislikes"
      resources :likes, path: "likes"
    end
    mount Commontator::Engine => '/commontator'
    resources :post_tags, path: "publicacoes_tags"
    resources :fusions, path: "fusoes"
    resources :project_users, path: "projeto_usuarios"
    resources :users, path: "usuarios"
    resources :boards, path: "diretorias"
    resources :cells, path: "celulas"
    resources :projects, path: "projetos"
    resources :tags, path: "tags"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task_cell.rb
class TaskCell < ApplicationRecord
  belongs_to :goal_cell

  validates :name, :description, :goal_cell_id, presence: true
end

app/controllers/task_cells_controller.rb
class TaskCellsController < ApplicationController
  load_and_authorize_resource
  before_action :set_task_cell, only: [:show, :edit, :update, :destroy]

  # GET /task_cells
  # GET /task_cells.json
  def index
    @task_cells = TaskCell.all
  end

  # GET /task_cells/1
  # GET /task_cells/1.json
  def show
  end

  # GET /task_cells/new
  def new
    @task_cell = TaskCell.new
  end

  # GET /task_cells/1/edit
  def edit
    @goal_cell = GoalCell.find(params[:goal_cell])
  end

  # POST /task_cells
  # POST /task_cells.json
  def create
    @task_cell = TaskCell.new(task_cell_params)

    respond_to do |format|
      if @task_cell.save
        goal_finished #Função para fazer com que a meta seja finalizada automaticamente quando todas as tarefas foram finalizadas
        format.html { redirect_to @task_cell, notice: 'Task cell was successfully created.' }
        format.json { render :show, status: :created, location: @task_cell }
      else
        format.html { render :new }
        format.json { render json: @task_cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_cells/1
  # PATCH/PUT /task_cells/1.json
  def update
    respond_to do |format|
      if @task_cell.update(task_cell_params)
        goal_finished #Função para fazer com que a meta seja finalizada automaticamente quando todas as tarefas foram finalizadas
        format.html { redirect_to @task_cell, notice: 'Task cell was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_cell }
      else
        format.html { render :edit }
        format.json { render json: @task_cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_cells/1
  # DELETE /task_cells/1.json
  def destroy
    @task_cell.destroy
    respond_to do |format|
      format.html { redirect_to task_cells_url, notice: 'Task cell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_cell
      @task_cell = TaskCell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_cell_params
      params.require(:task_cell).permit(:name, :description, :finished, :goal_cell_id)
    end

    def goal_finished #Função para fazer com que a meta seja finalizada automaticamente quando todas as tarefas foram finalizadas
      @tasks_finisheds = true
      @task_cell.goal_cell.task_cells.each do |task|  
        if task.finished == false
          @tasks_finisheds = false
        end
      end
      if @tasks_finisheds == true
        @task_cell.goal_cell.update(name: @task_cell.goal_cell.name, deadline: @task_cell.goal_cell.deadline, finished: true, cell_id: @task_cell.goal_cell.cell_id)
      else
        @task_cell.goal_cell.update(name: @task_cell.goal_cell.name, deadline: @task_cell.goal_cell.deadline, finished: false, cell_id: @task_cell.goal_cell.cell_id)
      end
    end
    
end

app/helpers/task_cells_helper.rb
module TaskCellsHelper
end

app/views/task_cells/_form.html.erb
<%= form_with(model: task_cell, local: true) do |form| %>
  <% if task_cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_cell.errors.count, "error") %> prohibited this task_cell from being saved:</h2>

      <ul>
      <% task_cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :finished %>
    <%= form.check_box :finished %>
  </div>

  <div class="field">
    <%= form.label :goal_cell_id %>
    <%= form.hidden_field :goal_cell_id, value: @goal_cell.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_cells/edit.html.erb
<h1>Editing Task Cell</h1>

<%= render 'form', task_cell: @task_cell %>

<%= link_to 'Show', @task_cell %> |
<%= link_to 'Back', goal_cell_path(@task_cell.goal_cell) %>

app/views/task_cells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Cells</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Finished</th>
      <th>Goal cell</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_cells.each do |task_cell| %>
      <tr>
        <td><%= task_cell.name %></td>
        <td><%= task_cell.description %></td>
        <td><%= task_cell.finished %></td>
        <td><%= task_cell.goal_cell %></td>
        <td><%= link_to 'Show', task_cell %></td>
        <td><%= link_to 'Edit', edit_task_cell_path(task_cell) %></td>
        <td><%= link_to 'Destroy', task_cell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Cell', new_task_cell_path %>

app/views/task_cells/new.html.erb
<h1>New Task Cell</h1>

<%= render 'form', task_cell: @task_cell %>

<%= link_to 'Back', task_cells_path %>

app/views/task_cells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_cell.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_cell.description %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @task_cell.finished %>
</p>

<p>
  <strong>Goal cell:</strong>
  <%= @task_cell.goal_cell %>
</p>

<%= link_to 'Edit', edit_task_cell_path(@task_cell) %> |
<%= link_to 'Back', task_cells_path %>