config/routes.rb
Rails.application.routes.draw do
  scope path_names: { new: "novo", edit: "editar" } do
    resources :project_tags, path: "projeto_tags"
    resources :task_cells, path: "tarefas_celulas"
    resources :task_boards, path: "tarefas_diretorias"
    resources :goal_cells, path: "meta_celulas"
    resources :goal_boards, path: "meta_diretorias"
    get "/users/new", to: "users#new"
    post "/users", to: "users#create"
    devise_for :users
    root to:  "static_pages#home"
    
    get "/artigos", to: "posts#articles", as: "articles"
    get "/artigos/novo", to: "posts#new_article", as: "new_article"
    get "/forum", to: "posts#forum"
    get "/tópico/novo", to: "posts#new_question", as: "new_question"
    
    resources :posts, path: "publicações" do
      resources :dislikes, path: "dislikes"
      resources :likes, path: "likes"
    end
    mount Commontator::Engine => '/commontator'
    resources :post_tags, path: "publicacoes_tags"
    resources :fusions, path: "fusoes"
    resources :project_users, path: "projeto_usuarios"
    resources :users, path: "usuarios"
    resources :boards, path: "diretorias"
    resources :cells, path: "celulas"
    resources :projects, path: "projetos"
    resources :tags, path: "tags"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  belongs_to :board
  belongs_to :cell

  #Relação N pra N
  has_many :historic_boards
  has_many :boards, through: :historic_boards

  #Relação N pra N
  has_many :historic_cells
  has_many :cells, through: :historic_cells

  acts_as_commontator

  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  
  has_many :posts

  #Relação N pra N
  has_many :project_users
  has_many :projects, through: :project_users

  #Relação N pra N
  has_many :fusions
  has_many :boards, through: :fusions

  validates :name, :age, :board_id, :board_kind,  presence: true
  validate :age_interval
  validate :validate_email
  validates :cell_id, :cell_kind, presence: true, if: :projects_board?

  enum board_kind: {
    director: 0,
    accessor: 1
  }

  enum cell_kind: {
    manager: 0,
    member: 1
  }

  private
    def projects_board? #TODO
      Board.find_by(name: "projetos")
    end
    
    def age_interval #Validação para saber se o usuário tem entre 0 e 200 anos
      if self.age < 0 || self.age > 200
        errors.add(:age_not_valid, "The age must be between 0 and 200 years")
      end
    end

    def validate_email #Validação para saber se o email é @injunior.com.br
      if a = self.email.index('@')
        if self.email[a..a+15] != "@injunior.com.br"
          errors.add(:email_not_injunior, "This email isn't part of a injunior's member")
        end
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_old_board, only: [:update]
  before_action :set_old_cell, only: [:update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @projects = @user.projects.where(finished: false) #Todos os projetos em andamento, no qual o usuario faz parte, para mostrar no show
    @projects_finisheds = @user.projects.where(finished: true) #Todos os projetos Finalizados, no qual o usuario é membro, para mostrar no show

    @articles = @user.posts.where(kind: "article") #Todos os artigos criados pelo usuario para aparecer no show
    @questions = @user.posts.where(kind: "question") #Todas as perguntas do usuário para aparecer no show
    
    @historic_boards = HistoricBoard.where(user_id: @user.id) #Histórico de Diretorias para aparecer no show do user
    @historic_cells = HistoricCell.where(user_id: @user.id) #Histórido de células para aparecer no show do user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|

      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }

        if @old_board != @user.board_id
          historic = HistoricBoard.create(user_id: @user.id, board_id: @old_board, departure: Time.now, entry: entry_time_board)
          historic.save
        end

        if @old_cell != @user.cell_id
          historic = HistoricCell.create(user_id: @user.id, cell_id: @old_cell, departure: Time.now, entry: entry_time_cell)
          historic.save
        end

      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:board_id, :cell_id, :name, :email, :password, :password_confirmation, :age, :cell_kind, :board_kind, :photo, :creation_cell)
    end

    def set_old_board
      @old_board = @user.board_id
    end

    def set_old_cell
      @old_cell = @user.cell_id
    end

    def entry_time_board
      if @user.historic_boards == []
        return @user.created_at
      else
        return @user.historic_boards.last.departure
      end
    end
    
    def entry_time_cell
      if @user.historic_cells == []
        return @user.created_at
      else
        return @user.historic_cells.last.departure
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
    def board_kind_options
        [["Diretor", :director], ["Acessor", :accessor]]
    end

    def cell_kind_options
        [["Gerente", :manager], ["Membro", :member]]
    end

    def fusion?
        if Fusion.find_by(user_id: @user.id)
            true
        else
            false
        end
    end

    def board_fusion
        if fusion?
            fusion = Fusion.find_by(user_id: @user.id)
            board_fusion = Board.find_by(id: fusion.board_id)
            return board_fusion
        end
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      
      <% user.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      
    </div>
  <% end %>

  <div class="register_big_div">

    <div class="register_field_name">
    
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, class: "field_name"%>
      
    </div>
    
    <div class="register_field_email">
        
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "field_email" %>
        
    </div>

    <div class="register_field_age">
      
        <%= f.label :age %>
        <%= f.number_field :age, autofocus: true, class: "field_age" %>
      
    </div>

    <div class="register_field_password">
      
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %>
        <%= f.password_field :password, autocomplete: "new-password", class: "field_password" %>
      
    </div>

    <div class="register_field_confirmation">
      
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "field_password" %>
      
    </div>
    
    <div class="register_field_photo">
            <%= f.label :photo %>
            <%= f.file_field :photo %>
        </div>

    <div class="register_field_creation">
          <%= f.label :creation_cell %>
          <%= f.check_box :creation_cell %>
    </div>  
    
    <div class="register_field_bid">
      
        <%= f.label "Diretoria" %>
        <%= f.collection_select(:board_id, Board.all, :id, :name, { :prompt => 'Escolha uma diretoria', :selected => @user.board_id }, { class: 'form-control' })%>
      
    </div>

    <div class="register_field_bkind">
      
        <%= f.label "Cargo" %>
        <%= f.select :board_kind, board_kind_options, class: "blue_box" %>
      
    </div> 

    <div class="register_field_cid">
      
        <%= f.label "Célula" %>
        <%= f.collection_select(:cell_id, Cell.all, :id, :name, { :prompt => 'Escolha uma celula', :selected => @user.cell_id }, { class: 'form-control' })%>
      
    </div>

    <div class="register_field_ckind">
      
        <%= f.label "Cargo" %>
        <%= f.select :cell_kind, cell_kind_options, class: "blue_box" %>
      
    </div>
  </div>

  <div class="register_actions">
    <%= f.submit "cadastrar", class:"register_button"  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Board</th>
      <th>Cell</th>
      <th>Name</th>
      <th>Age</th>
      <th>Cell kind</th>
      <th>Board kind</th>
      <th>Photo</th>
      <th>Creation cell</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.board.name %></td>
        <td><%= user.cell.name %></td>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.cell_kind %></td>
        <td><%= user.board_kind %></td>
        <td>
          <% if user.photo.present? %>
            <%= image_tag (user.photo.url) %>
          <% end %>
        </td>
        <td><%= user.creation_cell %></td>
        <td><%= link_to 'Show', user %></td>
        <%if can? :edit, User%>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <%end%>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, User %>
  <%= link_to 'New User', new_user_path %>
<% end %>

app/views/users/new.html.erb
<section id="register_title">
    <h1>cadastro</h1>
    <div class="register_line"></div>
</section>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="circle">
  <% if @user.photo.present? %>
    <strong></strong>
    <%= image_tag (@user.photo.url), class: "user_photo" %>
  <% end %>
</div>

<% if fusion? %>
  <%= @user.name + " está em fusão da diretoria " + Board.find_by(id: @user.board_id).name + " para " + board_fusion.name %>
<% end %>

<%= link_to  "Criar fusão", fusions_path %>

<div class="user_name">
  <p id="name">
    <strong></strong>
    <%= @user.name %> ,
  </p>

  <p id="age">
    <strong></strong>
    <%= @user.age %>
  </p>
</div>


<%if can? :edit, @user%>
  <%= link_to image_tag('edit.svg', :class => "user_icon"), edit_user_path(@user.id) %>
<%end%>


<div class="user_board">
  <p>
    <strong></strong>
    <%= @user.board.name %>
  </p>

  <p>
    <strong></strong>
    <%= @user.board_kind %>
  </p>

  <p>
    <strong></strong>
    <%= @user.cell.name %>
  </p>

  <p>
    <strong></strong>
    <%= @user.cell_kind %>
  </p>

  <p>
    <strong>Creation cell:</strong>
    <%= @user.creation_cell %>
  </p>
</div>



<div class="user_article">
  <p>
    <strong class="article">Articles</strong>
    <ul>
      <% @articles.each do |article| %>
        <li><%= link_to article.title, article %></li>
      <% end %>
    </ul>
  </p>
</div>

<div class="user_questions">
  <p>
    <strong class="questions">Questões no fórum</strong>
    <ul>
      <% @questions.each do |question| %>
        <li><%= link_to question.title, question %></li>
      <% end %>
    </ul>
  </p>
</div>

<div class="user_projects">
  <p class="projects">
    <strong >Projects</strong>
    <ul>
      <% @projects.each do |project| %>
        <li><%= link_to project.title, project %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong class="end_projects">Projects Finisheds</strong>

    <ul>
      <% @projects_finisheds.each do |project| %>
        <li><%= link_to project.title, project %></li>
      <% end %>
    </ul>
  </p>
</div>

<div class="user_history">
  <p class="history_board">
    <strong >Histórico de Diretorias</strong>
    <ul>
      <% @historic_boards.each do |historic| %>
        <li><%= Board.find_by(id: historic.board_id).name %></li>
        <li><%= "De #{ l historic.entry} até #{ l historic.departure}"%></li>
      <% end %>
    </ul>
  </p>

  <p class="history_cell">
    <strong >Histórico de Células</strong>

    <ul>
      <% @historic_cells.each do |historic| %>
        <li><%= Board.find_by(id: historic.cell_id).name %></li>
        <li><%= "De #{ l historic.entry} até #{ l historic.departure}" %></li>
      <% end %>
    </ul>
  </p>
</div>