config/routes.rb
Rails.application.routes.draw do
  scope path_names: { new: "novo", edit: "editar" } do
    resources :project_tags, path: "projeto_tags"
    resources :task_cells, path: "tarefas_celulas"
    resources :task_boards, path: "tarefas_diretorias"
    resources :goal_cells, path: "meta_celulas"
    resources :goal_boards, path: "meta_diretorias"
    get "/users/new", to: "users#new"
    post "/users", to: "users#create"
    devise_for :users
    root to:  "static_pages#home"
    
    get "/artigos", to: "posts#articles", as: "articles"
    get "/artigos/novo", to: "posts#new_article", as: "new_article"
    get "/forum", to: "posts#forum"
    get "/tópico/novo", to: "posts#new_question", as: "new_question"
    
    resources :posts, path: "publicações" do
      resources :dislikes, path: "dislikes"
      resources :likes, path: "likes"
    end
    mount Commontator::Engine => '/commontator'
    resources :post_tags, path: "publicacoes_tags"
    resources :fusions, path: "fusoes"
    resources :project_users, path: "projeto_usuarios"
    resources :users, path: "usuarios"
    resources :boards, path: "diretorias"
    resources :cells, path: "celulas"
    resources :projects, path: "projetos"
    resources :tags, path: "tags"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :user
  
  acts_as_commontable
  
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  
  #Relação N pra N
  has_many :post_tags
  has_many :tag, through: :post_tags

  enum kind: {
    article: 0,
    question: 1
  }

  validates :user_id, :title, :content, :kind, presence: true
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def articles
    @posts = Post.where(kind: "article")
    if (params[:tag] && params[:tag] != "")  && params[:title] != ""
      @articles = @posts.where(id: Tag.find_by(name: params[:tag]).post_ids, title: params[:title])
    elsif params[:title] && params[:title] != "" 
      @articles = @posts.where(title: params[:title])
    elsif params[:tag] && params[:tag] != "" 
      @articles = @posts.where(id: Tag.find_by(name: params[:tag]).post_ids)
    else
      @articles = @posts
    end
  end

  def forum
    @posts = Post.where(kind: "question")
    if (params[:tag] && params[:tag] != "")  && params[:title] != ""
      @forum = @posts.where(id: Tag.find_by(name: params[:tag]).post_ids, title: params[:title])
    elsif params[:title] && params[:title] != ""
      @forum = @posts.where(title: params[:title])
    elsif params[:tag] && params[:tag] != "" 
      @forum = @posts.where(id: Tag.find_by(name: params[:tag]).post_ids)
    else
      @forum = @posts
    end
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_tag = PostTag.new
    @tags = Tag.where(post: true)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def new_article
    @article = Post.new
  end

  def new_question
    @question = Post.new
  end


  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        #send_notification(@post.user, @post)
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to request.referrer }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content, :photo, :kind)
    end
 
    def send_notification(user, post)
      NotificationMailer.with(user: user, post:post).notification.deliver_now!
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def tags_select
        Tag.pluck(:name)
    end

end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <%= tinymce %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.hidden_field :kind, value: kind%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_show.html.erb
<div class="show_article">
  <div class="user_photo">
  <% if post.user.photo.present? %>
    <%= image_tag (post.user.photo.url) %>
  <% end %>
  </div>



  <div class="user_box">
    <p class="user_name">
      <%= post.user.name %>
    </p>
    <p class="user_board" >
    <%= "#{post.user.board_kind} de #{post.user.board.name}" %>
    </p>
  </div>
  
  <div class="post_photo">
    <% if post.photo.present? %>
        <%= image_tag (post.photo.url) %>
      <% end %>
  </div>


  <p class="post_title">
    <%= post.title%>
  </p>
  <%= tinymce %>

  <p class="post_content">
    <%= simple_format(post.content) %>
  </p>

  
  <p>
    <strong>Date:</strong>
    <%= post.created_at.to_date %>
  </p>

  <%= button_to 'Curtir', post_likes_path(post), method: :post, :class => "button"%>
  <p><%= post.likes.length%></p>

  <%= button_to 'Descurtir', post_dislikes_path(post), method: :post, :class => "button" %>
  <p><%= post.dislikes.length%></p>
  <%= link_to  "show", post %>
  <%if can? :edit, post%>
    <%= link_to 'Edit', edit_post_path(post) %>
  <%end%>
</div>

app/views/posts/articles.html.erb
<p id="notice"><%= notice %></p>

<div class="content">



  <section class="article">
      <h1>Artigos</h1>
      <div class="line"></div>

      <div class="search">
        <%= form_tag(articles_path, method: :get) do %>	
            Filtro:<%= select_tag :tag, options_for_select(tags_select),{:prompt => "escolha uma tag"} %>
            Titulo:<%= text_field_tag :title,params[:title] %>
            <%= submit_tag 'Search' , name: nil%>
        <% end %>
      </div>

      <div class="list">
        <% @articles.each do |article| %>
            
              <div class="article_box">
                <div class="photo">
                  <% if article.user.photo.present? %>
                    <%= image_tag (article.user.photo.url) %>
                  <% end %>
                </div>

                <div class="item">
                <%= link_to article.title, article, :class => "title" %>
                <div class="description"> 
                  criado por <%= article.user.name %>, em <%= l article.created_at.to_date%>
                
                <%if can? :edit, article%>
                    <%= link_to 'Editar', edit_post_path(article), :class => "button options" %>
                <%end%>
                <%if can? :destroy, article%>
                    <%= link_to 'Apagar', article, :class => "button options", method: :delete, data: { confirm: 'Tem certeza que deseja apagar?' } %>
                <%end%>
                </div>

                
                </div>
              </div>
            
        <% end %>
      

      <%= link_to 'Nova postagem', new_article_path, :class => "button" %>
      <div>
      <br>


    </section>
</div>

app/views/posts/edit.html.erb
<div class="edit_forum">
    <h1>Editar tópico</h1>
    <div class="line"></div>


    <%= render 'form', {post: @post, kind: @post.kind} %>
    </div>

app/views/posts/forum.html.erb
<section class="forum_list">
  <p id="notice"><%= notice %></p>

  <h1>Forum</h1>
  <div class="line"></div>

    <div class="search">
      <%= form_tag(forum_path, method: :get) do %>
        <%= select_tag :tag, options_for_select(tags_select),{:prompt => "escolha uma tag"} %>
        <%= text_field_tag :title,params[:title] %>
        <%= submit_tag 'Search' , name: nil%>
      <% end %>
    <div>

  

  
      <% @forum.each do |question| %>
          
            <div class="forum_box">
              <div class="item">
              <%= link_to question.title, question, :class => "title" %>
                <div class="description">
                  criado por <%= question.user.name %> em <%= l question.created_at %>
                  <%if can? :edit, question%>
                      <%= link_to 'Editar', edit_post_path(question), :class => "button options" %>
                  <%end%>
                  <%if can? :destroy, question%>
                      <%= link_to 'Apagar', question, :class => "button options", method: :delete, data: { confirm: 'Are you sure?' } %>
                  <%end%>
                </div>
              </div>
            </div>
            
      <% end %>

  <br>



  <%= link_to 'Novo tópico', new_question_path, :class => "button" %>
</section>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>Photo</th>
      <th>Kind</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.photo %></td>
        <td><%= post.kind %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new_article.html.erb
<div class="new_article">
    <h1>Novo artigo</h1>
    <div class="line"></div>

    <%= render 'form', {post: @article, kind: "article"} %>

</div>

app/views/posts/new_question.html.erb
<div class="new_topic">
    <h1>Novo tópico</h1>
    <div class="line"></div>

    <%= render 'form', {post: @question, kind: "question"} %>
</div>

app/views/posts/show.html.erb
<div class="show_article">
  <p id="notice"><%= notice %></p>
  <%if can? :edit, @post%>
    <%= render 'post_tags/form', {post_tag: @post_tag} %>
  <%end%>

 
      <% PostTag.all.each do |post_tag| %>
        <%if post_tag.post_id == @post.id %>
          <tr>
            <td><%= post_tag.tag.name %></td>
            <%if can? :edit, @post%>
              <td><%= link_to 'Destroy', post_tag, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
            <%end%>
          </tr>
        <%end%>
      <% end %>
  


  <div class="user_photo">
  <% if @post.user.photo.present? %>
    <%= image_tag (@post.user.photo.url) %>
  <% end %>
  </div>



  <div class="user_box">
    <p class="user_name">
      <%= @post.user.name %>
    </p>
    <p class="user_board" >
    <%= "#{@post.user.board_kind} de #{@post.user.board.name}" %>
    </p>
  </div>
  
  <div class="post_photo">
    <% if @post.photo.present? %>
        <%= image_tag (@post.photo.url) %>
      <% end %>
  </div>


  <p class="post_title">
    <%= @post.title%>
  </p>
  <%= tinymce %>

  <p class="post_content">
    <%= simple_format(@post.content) %>
  </p>

  
  <p>
    <strong>Date:</strong>
    <%= @post.created_at.to_date %>
  </p>

  <%= button_to 'Curtir', post_likes_path(@post), method: :post, :class => "button"%>
  <p><%=@post.likes.length%></p>

  <%= button_to 'Descurtir', post_dislikes_path(@post), method: :post, :class => "button" %>
  <p><%=@post.dislikes.length%></p>

  <%= commontator_thread(@post) %>



</div>